# Generated by Django 4.1 on 2023-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="recipe/",
                verbose_name="Фотография рецепта",
            ),
        ),
    ]
